[package]
name = "ppar"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"

[[bin]]
name = "perf"
required-features = ["perf"]

[[bin]]
name = "check"
required-features = ["check"]

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }

structopt = { version = "*", default-features = false, optional = true }
rand = { version = "0.7.3", features = ["small_rng"], optional = true}
im = { version = "15.0.0", optional = true }
im-rc = { version = "15.0.0", optional = true }

[dev-dependencies]
rpds = "0.7.0"
rand = { version = "0.7.3", features = ["small_rng"]}

[features]
perf = ["structopt", "rand", "im"]
check = ["structopt", "rand", "im"]
ppar-rc = ["im-rc"]
