[package]
name = "pary"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }

[dev-dependencies]
im = "15.0.0"
rand = { version = "0.7.3", features = ["small_rng"] }
